---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# BEGIN

sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0
  port: ${PORT:8080}
# END